// <auto-generated />
using System;
using Lottery.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lottery.Entities.Migrations
{
    [DbContext(typeof(LotteryDbContext))]
    [Migration("20221003060759_updateSample2")]
    partial class updateSample2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lottery.Entities.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2")
                        .HasComment("建立時間");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<DateTime?>("UpdateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("char(50)");

                    b.HasKey("Id");

                    b.ToTable("Sample");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDatetime = new DateTime(2022, 10, 3, 14, 7, 59, 671, DateTimeKind.Local).AddTicks(4729),
                            IsDelete = false,
                            Name = "類別A",
                            Sort = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateDatetime = new DateTime(2022, 10, 3, 14, 7, 59, 671, DateTimeKind.Local).AddTicks(4742),
                            IsDelete = false,
                            Name = "類別B",
                            Sort = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDatetime = new DateTime(2022, 10, 3, 14, 7, 59, 671, DateTimeKind.Local).AddTicks(4742),
                            IsDelete = false,
                            Name = "類別C",
                            Sort = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
